name: Release
on:
  workflow_dispatch:
    inputs:
      version:
        description: The new version type to publish. Must be one of patch, minor, or major.
        required: true
jobs:
  test:
    uses: ./.github/workflows/ci.yml
  build:
    runs-on: ubuntu-latest
    needs: ["test"]
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.RUPA_BUILDER }}
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      # Install
      - name: Install dependencies
        run: npm ci
      # Update version
      - name: Bump version
        run: |
          git config user.name github-actions
          git config user.email dev+github-actions@rupahealth.com
          npm version ${{ github.event.inputs.version }} -m "Release %s"
          git push
      # Build and publish
      - name: Publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      - name: Push to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.DEPLOY_AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.DEPOY_AWS_SECRET_ACCESS_KEY }}
        run: |
          npm build
          aws s3 sync ./dist s3://rupahealth-production-rupalabs-scripts/${{ github.event.inputs.version }}



