name: Publish package to npm
on:
  workflow_dispatch:
    inputs:
      version:
        description: The new version type to publish. Must be one of patch, minor, or major.
        required: true
jobs:
  test:
    uses: ./.github/workflows/test.yml
  build:
    runs-on: ubuntu-latest
    needs: ["test"]
    steps:
      - uses: actions/checkout@v3
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      # Install
      - run: npm ci
      # Update version
      - run: |
          git config user.name github-actions
          git config user.email dev+github-actions@rupahealth.com
          npm version ${{ github.event.inputs.version }}
      # Push new commit
      - run: git push
      # Build and publish
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
